-- ⚠️ DEPRECATED: This file is kept for reference only.
-- The actual database schema uses:
--   - user_roles table with app_role enum (super_admin, admin, manager, viewer, property_owner)
--   - profiles table WITHOUT a role column
--   - user_profiles_with_roles VIEW that joins profiles + user_roles
--   - has_role() security definer function for RLS policies
--
-- See supabase/migrations/ for the current schema.
