project_id = "jswumsdymlooeobrxict"

[functions.migrate-properties]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-status]
verify_jwt = false