project_id = "jswumsdymlooeobrxict"

[functions.import-properties-from-storage]
verify_jwt = false

[functions.migrate-properties]
verify_jwt = false

[functions.upload-properties-json]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-status]
verify_jwt = false