-- Step 1: Allow NULL values in neighborhood column
ALTER TABLE street_neighborhoods ALTER COLUMN neighborhood DROP NOT NULL;

-- Step 2: Add source column if it doesn't exist
ALTER TABLE street_neighborhoods ADD COLUMN IF NOT EXISTS source text DEFAULT 'manual';

-- Step 3: Insert new streets (only if not already exist)
INSERT INTO street_neighborhoods (city, street_name, neighborhood, source)
SELECT v.city, v.street_name, v.neighborhood, v.source
FROM (VALUES
  ('תל אביב יפו', 'אבא קובנר', NULL, 'wikisource'),
  ('תל אביב יפו', 'אבולעפיה', NULL, 'wikisource'),
  ('תל אביב יפו', 'אבן גבירול', 'מרכז_העיר', 'wikisource'),
  ('תל אביב יפו', 'אבן עזרא', NULL, 'wikisource'),
  ('תל אביב יפו', 'אברבנאל', NULL, 'wikisource'),
  ('תל אביב יפו', 'אהבת ציון', NULL, 'wikisource'),
  ('תל אביב יפו', 'אהרונוביץ', NULL, 'wikisource'),
  ('תל אביב יפו', 'אוסישקין', NULL, 'wikisource'),
  ('תל אביב יפו', 'אופנהיימר', NULL, 'wikisource'),
  ('תל אביב יפו', 'אורי צבי גרינברג', NULL, 'wikisource'),
  ('תל אביב יפו', 'אחד העם', 'רוטשילד', 'wikisource'),
  ('תל אביב יפו', 'אחוזת בית', NULL, 'wikisource'),
  ('תל אביב יפו', 'איילון', NULL, 'wikisource'),
  ('תל אביב יפו', 'אימבר', NULL, 'wikisource'),
  ('תל אביב יפו', 'אלוף קלמן מגן', 'רמת_אביב', 'wikisource'),
  ('תל אביב יפו', 'אלחריזי', NULL, 'wikisource'),
  ('תל אביב יפו', 'אמיל זולא', NULL, 'wikisource'),
  ('תל אביב יפו', 'אסירי ציון', NULL, 'wikisource'),
  ('תל אביב יפו', 'בארי', NULL, 'wikisource'),
  ('תל אביב יפו', 'בוסל', NULL, 'wikisource'),
  ('תל אביב יפו', 'בוסתנאי', NULL, 'wikisource'),
  ('תל אביב יפו', 'בורוכוב', NULL, 'wikisource'),
  ('תל אביב יפו', 'ביאליק', 'מרכז_העיר', 'wikisource'),
  ('תל אביב יפו', 'בילו', NULL, 'wikisource'),
  ('תל אביב יפו', 'בית הבד', NULL, 'wikisource'),
  ('תל אביב יפו', 'בלפור', NULL, 'wikisource'),
  ('תל אביב יפו', 'בן אביגדור', NULL, 'wikisource'),
  ('תל אביב יפו', 'בן סרוק', NULL, 'wikisource'),
  ('תל אביב יפו', 'בן ציון', NULL, 'wikisource'),
  ('תל אביב יפו', 'בני אפרים', NULL, 'wikisource'),
  ('תל אביב יפו', 'בני דן', NULL, 'wikisource'),
  ('תל אביב יפו', 'בני משה', NULL, 'wikisource'),
  ('תל אביב יפו', 'בצלאל', NULL, 'wikisource'),
  ('תל אביב יפו', 'ברודצקי', 'רמת_אביב', 'wikisource'),
  ('תל אביב יפו', 'ברוריה', NULL, 'wikisource'),
  ('תל אביב יפו', 'ברזילי', NULL, 'wikisource'),
  ('תל אביב יפו', 'ברנר', NULL, 'wikisource'),
  ('תל אביב יפו', 'גאולה', NULL, 'wikisource'),
  ('תל אביב יפו', 'גבעון', NULL, 'wikisource'),
  ('תל אביב יפו', 'גולומב', NULL, 'wikisource'),
  ('תל אביב יפו', 'גוש עציון', NULL, 'wikisource'),
  ('תל אביב יפו', 'גיסין', NULL, 'wikisource'),
  ('תל אביב יפו', 'גלילי', NULL, 'wikisource'),
  ('תל אביב יפו', 'גנסין', NULL, 'wikisource'),
  ('תל אביב יפו', 'גרוזנברג', NULL, 'wikisource'),
  ('תל אביב יפו', 'דב הוז', NULL, 'wikisource'),
  ('תל אביב יפו', 'דבורה הנביאה', NULL, 'wikisource'),
  ('תל אביב יפו', 'דובנוב', NULL, 'wikisource'),
  ('תל אביב יפו', 'דוד פרישמן', 'מרכז_העיר', 'wikisource'),
  ('תל אביב יפו', 'דונש בן לברט', NULL, 'wikisource'),
  ('תל אביב יפו', 'דיין', NULL, 'wikisource'),
  ('תל אביב יפו', 'דרויאנוב', NULL, 'wikisource'),
  ('תל אביב יפו', 'דרך בגין', NULL, 'wikisource'),
  ('תל אביב יפו', 'דרך השלום', NULL, 'wikisource'),
  ('תל אביב יפו', 'דרך יפו', NULL, 'wikisource'),
  ('תל אביב יפו', 'דרך נמיר', 'צפון_חדש', 'wikisource'),
  ('תל אביב יפו', 'דרך פתח תקוה', NULL, 'wikisource'),
  ('תל אביב יפו', 'האמוראים', NULL, 'wikisource'),
  ('תל אביב יפו', 'הבנים', NULL, 'wikisource'),
  ('תל אביב יפו', 'הגדוד העברי', NULL, 'wikisource'),
  ('תל אביב יפו', 'ההגנה', NULL, 'wikisource'),
  ('תל אביב יפו', 'הושע', NULL, 'wikisource'),
  ('תל אביב יפו', 'החשמונאים', NULL, 'wikisource'),
  ('תל אביב יפו', 'הילל', NULL, 'wikisource'),
  ('תל אביב יפו', 'היצירה', NULL, 'wikisource'),
  ('תל אביב יפו', 'הכוזרי', NULL, 'wikisource'),
  ('תל אביב יפו', 'הכנסת', NULL, 'wikisource'),
  ('תל אביב יפו', 'המגיד', NULL, 'wikisource'),
  ('תל אביב יפו', 'המלאכה', NULL, 'wikisource'),
  ('תל אביב יפו', 'המעפילים', NULL, 'wikisource'),
  ('תל אביב יפו', 'הנביאים', NULL, 'wikisource'),
  ('תל אביב יפו', 'הנגב', NULL, 'wikisource'),
  ('תל אביב יפו', 'הס', NULL, 'wikisource'),
  ('תל אביב יפו', 'העליה', NULL, 'wikisource'),
  ('תל אביב יפו', 'הצפירה', NULL, 'wikisource'),
  ('תל אביב יפו', 'הקונגרס', NULL, 'wikisource'),
  ('תל אביב יפו', 'הראשונים', NULL, 'wikisource'),
  ('תל אביב יפו', 'הרב מיימון', NULL, 'wikisource'),
  ('תל אביב יפו', 'הרב קוק', NULL, 'wikisource'),
  ('תל אביב יפו', 'הרברט סמואל', 'מרכז_העיר', 'wikisource'),
  ('תל אביב יפו', 'הרצל', 'מרכז_העיר', 'wikisource'),
  ('תל אביב יפו', 'השומר', NULL, 'wikisource'),
  ('תל אביב יפו', 'התנאים', NULL, 'wikisource'),
  ('תל אביב יפו', 'וולפסון', NULL, 'wikisource'),
  ('תל אביב יפו', 'ורבורג', NULL, 'wikisource'),
  ('תל אביב יפו', 'זבולון', NULL, 'wikisource'),
  ('תל אביב יפו', 'זכרון יעקב', NULL, 'wikisource'),
  ('תל אביב יפו', 'זמנהוף', NULL, 'wikisource'),
  ('תל אביב יפו', 'זרובבל', NULL, 'wikisource'),
  ('תל אביב יפו', 'חובבי ציון', NULL, 'wikisource'),
  ('תל אביב יפו', 'חומה ומגדל', NULL, 'wikisource'),
  ('תל אביב יפו', 'חנה סנש', NULL, 'wikisource'),
  ('תל אביב יפו', 'חפץ חיים', NULL, 'wikisource'),
  ('תל אביב יפו', 'טבנקין', NULL, 'wikisource'),
  ('תל אביב יפו', 'טהון', NULL, 'wikisource'),
  ('תל אביב יפו', 'טרומפלדור', NULL, 'wikisource'),
  ('תל אביב יפו', 'יבנה', NULL, 'wikisource'),
  ('תל אביב יפו', 'יהודה הימית', NULL, 'wikisource'),
  ('תל אביב יפו', 'יהודה הלוי', 'מרכז_העיר', 'wikisource'),
  ('תל אביב יפו', 'יהודה מרגוזה', NULL, 'wikisource'),
  ('תל אביב יפו', 'יונה הנביא', NULL, 'wikisource'),
  ('תל אביב יפו', 'יחזקאל', NULL, 'wikisource'),
  ('תל אביב יפו', 'ים סוף', NULL, 'wikisource'),
  ('תל אביב יפו', 'יעבץ', NULL, 'wikisource'),
  ('תל אביב יפו', 'יפה נוף', NULL, 'wikisource'),
  ('תל אביב יפו', 'ירמיה', NULL, 'wikisource'),
  ('תל אביב יפו', 'ישעיהו', NULL, 'wikisource'),
  ('תל אביב יפו', 'כורזין', NULL, 'wikisource'),
  ('תל אביב יפו', 'כיכר דיזנגוף', 'מרכז_העיר', 'wikisource'),
  ('תל אביב יפו', 'כיכר המדינה', 'כיכר_המדינה', 'wikisource'),
  ('תל אביב יפו', 'כיכר רבין', NULL, 'wikisource'),
  ('תל אביב יפו', 'כנרת', NULL, 'wikisource'),
  ('תל אביב יפו', 'כצנלסון', NULL, 'wikisource'),
  ('תל אביב יפו', 'כרמיה', NULL, 'wikisource'),
  ('תל אביב יפו', 'לוינסקי', NULL, 'wikisource'),
  ('תל אביב יפו', 'לטריס', NULL, 'wikisource'),
  ('תל אביב יפו', 'ליבנה', NULL, 'wikisource'),
  ('תל אביב יפו', 'לילינבלום', 'רוטשילד', 'wikisource'),
  ('תל אביב יפו', 'לנדאו', NULL, 'wikisource'),
  ('תל אביב יפו', 'מאנה', NULL, 'wikisource'),
  ('תל אביב יפו', 'מאפו', NULL, 'wikisource'),
  ('תל אביב יפו', 'מבצע קדש', NULL, 'wikisource'),
  ('תל אביב יפו', 'מגדל', NULL, 'wikisource'),
  ('תל אביב יפו', 'מודיעין', NULL, 'wikisource'),
  ('תל אביב יפו', 'מונטיפיורי', 'רוטשילד', 'wikisource'),
  ('תל אביב יפו', 'מוצקין', NULL, 'wikisource'),
  ('תל אביב יפו', 'מיכה', NULL, 'wikisource'),
  ('תל אביב יפו', 'מלכי ישראל', NULL, 'wikisource'),
  ('תל אביב יפו', 'מנדלי', NULL, 'wikisource'),
  ('תל אביב יפו', 'מסריק', NULL, 'wikisource'),
  ('תל אביב יפו', 'מרדכי', NULL, 'wikisource'),
  ('תל אביב יפו', 'מרים החשמונאית', NULL, 'wikisource'),
  ('תל אביב יפו', 'משה שרת', NULL, 'wikisource'),
  ('תל אביב יפו', 'נחלת בנימין', 'מרכז_העיר', 'wikisource'),
  ('תל אביב יפו', 'נחלת יצחק', NULL, 'wikisource'),
  ('תל אביב יפו', 'נחמיה', NULL, 'wikisource'),
  ('תל אביב יפו', 'נחשון', NULL, 'wikisource'),
  ('תל אביב יפו', 'ניסנבאום', NULL, 'wikisource'),
  ('תל אביב יפו', 'נעמי', NULL, 'wikisource'),
  ('תל אביב יפו', 'סירקין', NULL, 'wikisource'),
  ('תל אביב יפו', 'סלמה', NULL, 'wikisource'),
  ('תל אביב יפו', 'סמילנסקי', NULL, 'wikisource'),
  ('תל אביב יפו', 'סנהדרין', NULL, 'wikisource'),
  ('תל אביב יפו', 'סעדיה גאון', NULL, 'wikisource'),
  ('תל אביב יפו', 'עולי ציון', NULL, 'wikisource'),
  ('תל אביב יפו', 'עזרא הסופר', NULL, 'wikisource'),
  ('תל אביב יפו', 'עליית הנוער', NULL, 'wikisource'),
  ('תל אביב יפו', 'עמוס', NULL, 'wikisource'),
  ('תל אביב יפו', 'עמישב', NULL, 'wikisource'),
  ('תל אביב יפו', 'ענתבי', NULL, 'wikisource'),
  ('תל אביב יפו', 'פדויים', NULL, 'wikisource'),
  ('תל אביב יפו', 'פומבדיתא', NULL, 'wikisource'),
  ('תל אביב יפו', 'פין', NULL, 'wikisource'),
  ('תל אביב יפו', 'פינסקר', NULL, 'wikisource'),
  ('תל אביב יפו', 'פלורנטין', 'פלורנטין', 'wikisource'),
  ('תל אביב יפו', 'פרוג', NULL, 'wikisource'),
  ('תל אביב יפו', 'פרץ', NULL, 'wikisource'),
  ('תל אביב יפו', 'צבי שפירא', NULL, 'wikisource'),
  ('תל אביב יפו', 'צייטלין', NULL, 'wikisource'),
  ('תל אביב יפו', 'צמח', NULL, 'wikisource'),
  ('תל אביב יפו', 'צפניה', NULL, 'wikisource'),
  ('תל אביב יפו', 'קארו', NULL, 'wikisource'),
  ('תל אביב יפו', 'קדושי קהיר', NULL, 'wikisource'),
  ('תל אביב יפו', 'קהילת סלוניקי', NULL, 'wikisource'),
  ('תל אביב יפו', 'קהילת ציון', NULL, 'wikisource'),
  ('תל אביב יפו', 'קלונימוס', NULL, 'wikisource'),
  ('תל אביב יפו', 'קלישר', NULL, 'wikisource'),
  ('תל אביב יפו', 'קפלנסקי', NULL, 'wikisource'),
  ('תל אביב יפו', 'קרית ספר', NULL, 'wikisource'),
  ('תל אביב יפו', 'קרליבך', NULL, 'wikisource'),
  ('תל אביב יפו', 'רב אשי', NULL, 'wikisource'),
  ('תל אביב יפו', 'רבי טרפון', NULL, 'wikisource'),
  ('תל אביב יפו', 'רבי מאיר', NULL, 'wikisource'),
  ('תל אביב יפו', 'רבי עקיבא', NULL, 'wikisource'),
  ('תל אביב יפו', 'רוזן', NULL, 'wikisource'),
  ('תל אביב יפו', 'רופין', NULL, 'wikisource'),
  ('תל אביב יפו', 'רזיאל', 'צהלה', 'wikisource'),
  ('תל אביב יפו', 'רייך', NULL, 'wikisource'),
  ('תל אביב יפו', 'רייק', NULL, 'wikisource'),
  ('תל אביב יפו', 'רייס', NULL, 'wikisource'),
  ('תל אביב יפו', 'רינה', NULL, 'wikisource'),
  ('תל אביב יפו', 'רמז', NULL, 'wikisource'),
  ('תל אביב יפו', 'שאול המלך', 'בבלי', 'wikisource'),
  ('תל אביב יפו', 'שבט לוי', NULL, 'wikisource'),
  ('תל אביב יפו', 'שבטי ישראל', NULL, 'wikisource'),
  ('תל אביב יפו', 'שד בן גוריון', 'צפון_ישן', 'wikisource'),
  ('תל אביב יפו', 'שד ירושלים', NULL, 'wikisource'),
  ('תל אביב יפו', 'שד נורדאו', 'צפון_ישן', 'wikisource'),
  ('תל אביב יפו', 'שד רוקח', NULL, 'wikisource'),
  ('תל אביב יפו', 'שד שאול המלך', 'בבלי', 'wikisource'),
  ('תל אביב יפו', 'שדה בוקר', NULL, 'wikisource'),
  ('תל אביב יפו', 'שושנה דמארי', NULL, 'wikisource'),
  ('תל אביב יפו', 'שחר', NULL, 'wikisource'),
  ('תל אביב יפו', 'שטרן', NULL, 'wikisource'),
  ('תל אביב יפו', 'שי עגנון', NULL, 'wikisource'),
  ('תל אביב יפו', 'שינקין', 'מרכז_העיר', 'wikisource'),
  ('תל אביב יפו', 'שלום אש', NULL, 'wikisource'),
  ('תל אביב יפו', 'שלום עליכם', NULL, 'wikisource'),
  ('תל אביב יפו', 'שלמה המלך', NULL, 'wikisource'),
  ('תל אביב יפו', 'שמאי', NULL, 'wikisource'),
  ('תל אביב יפו', 'שמואל', NULL, 'wikisource'),
  ('תל אביב יפו', 'שמואל הנביא', NULL, 'wikisource'),
  ('תל אביב יפו', 'שמעון הצדיק', NULL, 'wikisource'),
  ('תל אביב יפו', 'שמשון', NULL, 'wikisource'),
  ('תל אביב יפו', 'שפינוזה', NULL, 'wikisource'),
  ('תל אביב יפו', 'שפרינצק', NULL, 'wikisource'),
  ('תל אביב יפו', 'שרה אהרונסון', NULL, 'wikisource'),
  ('תל אביב יפו', 'שרון', NULL, 'wikisource'),
  ('תל אביב יפו', 'תוצרת הארץ', NULL, 'wikisource'),
  ('תל אביב יפו', 'תחכמוני', NULL, 'wikisource')
) AS v(city, street_name, neighborhood, source)
WHERE NOT EXISTS (
  SELECT 1 FROM street_neighborhoods sn
  WHERE sn.city = v.city AND sn.street_name = v.street_name
);