// This file may be auto-generated by tooling. Keep it minimal and env-driven.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL =
  (import.meta.env.VITE_SUPABASE_URL as string | undefined) ??
  (import.meta.env.SUPABASE_URL as string | undefined);

const SUPABASE_ANON_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ??
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ??
  (import.meta.env.SUPABASE_PUBLISHABLE_KEY as string | undefined) ??
  (import.meta.env.SUPABASE_ANON_KEY as string | undefined);

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("[Supabase] env check:", {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_ANON_KEY,
  });
  throw new Error(
    "Missing Supabase env: set VITE_SUPABASE_URL + one of VITE_SUPABASE_PUBLISHABLE_KEY / VITE_SUPABASE_ANON_KEY"
  );
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
